### ISSUE TITLE
Some questions about the SCAN

### ISSUE THREAD

**Issue by shuxjweb** [AsuradaYuci/SCAN_pytorch#1]
Hi, thank you for contributing this codes. I have runned your code, but I cannot achieve similar results in paper. 
1. The top-1 is from 80% to 83.3% with optical flow for iLIDS. I don't know why?
2. I print information while running, the prec_score is always 75%, that is quite strange.
3. The learning rate of backbone degrades slower than attention module and classifier, namely, the lr of backbone is larger , why?
lr = args.lr1 * (0.1 ** (epoch/args.lr1step))
lr = args.lr2 * (0.01 ** (epoch//args.lr2step))

3. I cannot find the script "marssequence.py", can you share it for me, thanks.

**Comment by AsuradaYuci** [comment]
@shuxjweb 1. I have not run the code on the iLIDS dataset, so I don't know the performance about this dataset.
2. The reason for **prec_score is always 75%** is that I comment some code in **/reid/models/classifier.py line 49 => diff = self.classifierBN(diff)**, you can remove the '#' and I think prec_score will get 100%。
3. I have no idea about lr, you can explore the setting of 'lr' by yourself. Maybe for attention module and classifier, it's easier to learn compared with backbone.
4. As Mars dataset is very different with another two datasets, we should change some (maybe much) code in other '.py' files, so marssequence.py is not provided.
